### ISSUE TITLE
Documentation About broken links

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#100]
Broken Links:
- [x] [Research Community](https://docs.biocomputeobject.org/research) -> 404 page
- [x] [Clinical Community](https://docs.biocomputeobject.org/clinical) -> 404 page
- [x] [Pharma, Biotech and Regulatory Pipeline](https://docs.biocomputeobject.org/regulatory) -> 404 page
- [x] [Research Objects discussion of BioCompute](http://www.researchobject.org/2017-11-27-biocompute-objects/) -> 404 page
- [x] [Executive Committee](https://www.biocomputeobject.org/leadership.html)  ->[ Leads to biocompute login page](https://www.biocomputeobject.org/login)

**Comment by jpat1546** [comment]
These have all been resolved (fixed/pages archived/etc.)
