### ISSUE TITLE
BCO Curation SOP errors

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#102]
At [Curation SOP](https://docs.biocomputeobject.org/sop) the [BCO Consortium Editor tool](https://portal.aws.biochemistry.gwu.edu/sign-in) link leads to the depreciated AWS portal

**Comment by jpat1546** [comment]
Fixed link https://github.com/biocompute-objects/BCO_Specification/commit/42dd6e440fede5265b2427c1e55582fc95632c9a
