### ISSUE TITLE
One of the hyperlinks in Documentation Home not working

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/BCO_Specification#108]
# **Describe the bug**
Hyperlink for "The BioCompute Object working group" showing "404 page not found"

# **To Reproduce**
1. Go to https://docs.biocomputeobject.org/
2. Find and click on 'The BioCOmpute Object working group' hyperlink
3. See error

**Comment by HadleyKing** [comment]
[221ac9e](https://github.com/biocompute-objects/BCO_Specification/commit/221ac9e9f58fac55aeea4d9356e2c4f2fb8c6724)
