### ISSUE TITLE
What is a type?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#11]
[type](https://github.com/biocompute-objects/BCO_Specification/blob/master/top-level.md#202-type-type) is explained as if one is already meant to know how types are declared.

> As any object of type 'type,' it has its own fields: `_type`, `_id`, `_inherits`, `name`, `title` and `description`. Type of this JSON object is "antiviral_resistance_detection"

The meaning of these fields are nowhere explained, and this typing system is not explained. 

Suggestion is to remove the `type` field or to add a section that explain the typing system. [data-typing.md](https://github.com/biocompute-objects/BCO_Specification/blob/master/data-typing.md) might be an early attempt of this, but it has no technical information.

**Comment by HadleyKing** [comment]
After the virtual rooms from the [BioCompute Spec Hack-a-thon]() closed yesterday  @rajamazumder @anton-golikov @kee007ney @kkaragiannis @rykahsay and I all discussed this. When the BCO spec was first being developed [JSON Schema](https://json-schema.org/) did not exist.  The [`_type`](https://github.com/biocompute-objects/BCO_Specification/blob/master/base_type_BioCompute.json) and [`type`](https://github.com/biocompute-objects/BCO_Specification/blob/master/antiviral_resistance_detectionTypeDef.json) and the [primitives](https://github.com/biocompute-objects/BCO_Specification/blob/master/primitives.json) were all an attempt to do what has been done in JSON schema.

**Comment by mr-c** [comment]
@HadleyKing Okay, so will we be removing this from the BCO spec?
