### ISSUE TITLE
Unclickable logos

### ISSUE THREAD

**Issue by tiwa1154** [biocompute-objects/BCO_Specification#110]
# **Describe the bug**
*Both HIVE logo and Galaxy logo are unclickable on the home page.*

# **To Reproduce**
*Steps to reproduce the behavior:*
1. Go to https://test.portal.biochemistry.gwu.edu/
2. Click on HIVE logo or Galaxy logo
3. Neither logo has a response

# **Desktop (please complete the following information):**
 macOS Monterey - Firefox 

# **Additional context**
Based on the Portal Testing document, both logos should have redirect links.

**Comment by HadleyKing** [comment]
Links are no longer live
