### ISSUE TITLE
Wiki Transfer Status

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#111]
Wiki Transfer Status 
-- |
-   [x] | _index.md
-   [x] | about.md
-   [x] | bco-domains.md
-   [x] | best_practices.md
-   [ ] | contact.md
-   [ ] | definitions.md
-   [x] | description-domain.md
-   [x] | error-domain.md
-   [ ] | events.md
-   [x] | execution-domain.md
-   [x] | extension-domain.md
-   [x] | extension-fhir.md
-   [x] | extension-scm.md
-   [x] | external-references.md
-   [x] | faq.md
-   [ ] | galaxy_quick_start.md
-   [x] | introduction.md
-   [x] | io-domain.md
-   [ ] | leadership.md
-   [ ] | news.md
-   [ ] | organization.md
-   [x] | parametric-domain.md
-   [ ] | ppp.md
-   [x] | provenance-domain.md
-   [x] | quick_start.md
-   [ ] | release_protocol.md
-   [ ] | services.md
-   [x] | sop.md
-   [x] | top-level.md
-   [x] | usability-domain.md
-   [x] | user_guide.md

**Comment by tiwa1154** [comment]
best_practices.md and definitions.md have the same content.
