### ISSUE TITLE
Keywords should not be nested

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#12]
The [keywords](https://github.com/biocompute-objects/BCO_Specification/blob/master/description-domain.md#241-keywords-keywords) is for some reason nested as a map to lists.

```json
      "keywords": [
            {
                "key": "search terms",
                "value": [
                    "HCV1a", 
                    "Ledipasvir", 
                    "antiviral resistance", 
                    "SNP", 
                    "amino acid substitutions"
                ]
            }
        ]
```

It is unclear what is the meaning of nestings like `search terms` and where such keys should be defined.

Keywords are normally not structured, so I would change this to a flat listing:

```json
      "keywords": [
                    "HCV1a", 
                    "Ledipasvir", 
                    "antiviral resistance", 
                    "SNP", 
                    "amino acid substitutions"
        ]
```

**Comment by HadleyKing** [comment]
agreed.

**Comment by mr-c** [comment]
Fixed in https://github.com/biocompute-objects/BCO_Specification/commit/d0aa195bdbd64ce43291277affcbec7f02cb56a5
