### ISSUE TITLE
Explain keys of prerequisite

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#13]
[prerequisite](https://github.com/biocompute-objects/BCO_Specification/blob/master/description-domain.md#2434-tool-prerequisites-prerequisite) has inconsistent definition:

> A list of text values to indicate any packages or prerequisites for running the tool used.

Yet it is shown as example with sub-keys that are not defined anywhere:

```json
                    "prerequisite": [
                        {
                            "name": "Hepatitis C virus genotype 1", 
                            "source": {
                                "address": "http://www.ncbi.nlm.nih.gov/nuccore/22129792",
                                "access_time": "2017-01-24T09:40:17-0500"
                            }
                        }, 
                        {
                            "name": "Hepatitis C virus type 1b complete genome", 
                            "source": {
                                "address": "http://www.ncbi.nlm.nih.gov/nuccore/5420376",
                                "access_time": "2017-01-24T09:40:17-0500"
                            }
                        }, 
```

The text needs to explain what is the meaning of `name`, `source`, `address` and `access_time`. Some examples use [other keys](https://github.com/biocompute-objects/BCO_Specification/blob/master/HCV1a.json#L230) like `uri` `version` and `sha1_chksum` which are not defined anywhere.

If `prerequisite` is a free-for-all in terms of keys this should be defined, although it can be argued over how useful that will be.

**Comment by HadleyKing** [comment]
In the [base_type_BioCompute.json](https://github.com/biocompute-objects/BCO_Specification/blob/master/base_type_BioCompute.json#L173) `source` is defined as a `uri`, inheriting from [primitives.json](https://github.com/biocompute-objects/BCO_Specification/blob/master/primitives.json#L50). 

Changing `source` to `uri` is a simple fix.
