### ISSUE TITLE
How are templates expanded in structured_name?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#14]
[structured_name](https://github.com/biocompute-objects/BCO_Specification/blob/master/provenance-domain.md#212--structured-name-structured_name) seems to define a simple template system:

> This field can refer to other fields within the same or other objects. For example, a string like "HCV1a [taxonomy:$taxonomy] mutation detection"

It is not defined what is the syntax for the `$magic` variable, neither if this is restricted to looking up direct neighbouring keys of `provenance_domain`.

The example also seems to imply that adding arbitrary non-namespaced keys like `taxonomy` is allowed, but nowhere else is this clarified.

This should be clarified or removed.

**Comment by stain** [comment]
[JSON Pointer](https://tools.ietf.org/html/rfc6901) might be one way to do the referencing.  [Relative JSON pointers](https://datatracker.ietf.org/doc/draft-handrews-relative-json-pointer/) might be better for resolving neighbours.

**Comment by HadleyKing** [comment]
This field was created to fulfill a function that it is not doing in it's current state. The thought was to have a field that was automatically generated based on the templated info already present in the BCO. I believe at this stage that it is out side the scope of what we need to develop working examples. I think we should re-examine this at a later date. I am going to remove this field for the time being.
