### ISSUE TITLE
Are arbitrary extra keys allowed?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#15]
In the example for [structured_name](https://github.com/biocompute-objects/BCO_Specification/blob/master/provenance-domain.md#212--structured-name-structured_name) the arbitrary key `taxonomy` is introduced. (See #14)

Several other examples also use extra keys.  

It might be powerful to allow BCO extensions to add more fields, but I thought we already had `extension_domain` for that. 

It must be declared if arbitrary extra keys are allowed or not (and where). If they are allowed I would recommend they are namespaced so that they are not in conflict across vendors or future BCO versions.

**Comment by HadleyKing** [comment]
> It might be powerful to allow BCO extensions to add more fields, but I thought we already had `extension_domain` for that.

Yes. That is the intention.
Only the defined keys should be permitted. As the `structured_name` is on hold for now, we can close this issue.
