### ISSUE TITLE
Define keys of review object

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#16]
The [review](https://github.com/biocompute-objects/BCO_Specification/blob/master/provenance-domain.md#214-review-review) object is only shown by example.

The sub-keys `reviewer_comment` and `reviewer` must be further defined. For instance, why is `reviewer_comment` a list?

The possible values for `status` should be defined as a bullet-point list rather than inline in a text, so that is clear what are the only possible values.

**Comment by corburn** [comment]
@jpat1546 should `_multi_value` likewise be removed from `reviewer`:

https://github.com/biocompute-objects/BCO_Specification/blob/ef7f70f9b86f44fcd116c19d874112c6c055eccb/base_type_BioCompute.json#L73-L76

to match the example:

https://github.com/biocompute-objects/BCO_Specification/blame/ef7f70f9b86f44fcd116c19d874112c6c055eccb/provenance-domain.md#L74-L80

**Comment by HadleyKing** [comment]
@corburn - 

> should `_multi_value` likewise be removed from `reviewer`:
> 
> [BCO_Specification/base_type_BioCompute.json](https://github.com/biocompute-objects/BCO_Specification/blob/ef7f70f9b86f44fcd116c19d874112c6c055eccb/base_type_BioCompute.json#L73-L76)
> 
> Lines 73 to 76 in [ef7f70f](/biocompute-objects/BCO_Specification/commit/ef7f70f9b86f44fcd116c19d874112c6c055eccb)
> 
>  "reviewer" : { 
>      "_type": "contributor", 
>      "_multi_value" : true 
>  }, 
> to match the example:
> 
> https://github.com/biocompute-objects/BCO_Specification/blame/ef7f70f9b86f44fcd116c19d874112c6c055eccb/provenance-domain.md#L74-L80

Reviewer inherits the `contributor` object, and that object should have a `_multi_value` for the
