### ISSUE TITLE
Recommend Semantic Versioning for version field?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#17]
The [version](https://github.com/biocompute-objects/BCO_Specification/blob/master/provenance-domain.md#213-version-version) field defines briefly what constitutes a change of a BCO.

We should recommend using https://semver.org/ (e.g. `1.2.0`) so that there is also a clear semantics on how to compare version numbers to determine which BCO is "newer" in what way.

As pointed out in #8 we also need to be clear if such a change should constitute a change of `BCO_id` or not.

**Comment by mr-c** [comment]
https://github.com/biocompute-objects/BCO_Specification/commit/540630e7317063e558a210ccc6a4f9c81276e875#diff-62f9f0f6302589910bf23cb5843752acR25
`"_comment": "suggestion major[.minor[.build_nunber]] as described at https://semver.org/"`

`build_nunber` [sic] nor `build_number` is defined at semver.org, the overall pattern is `MAJOR.MINOR.PATCH`
