### ISSUE TITLE
What is a derived_from objectId

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#18]
[derived_from](https://github.com/biocompute-objects/BCO_Specification/blob/master/provenance-domain.md#215-inheritancederivation-derived_from) says:

> If the object is derived from another, this field will specify the parent object, in the form of the ‘objectid’. If the object inherits only from the base BioCompute Object or a type definition than the value here is null.

Is is unclear what is an _objectid_. Is this different from a `BCO_id` of the other BCO? (which we said was a URI)

The example is shown with `null` - rather this should be shown with a value.

See also #9

**Comment by HadleyKing** [comment]
This should be a BCO_ID, needs to be explained...
