### ISSUE TITLE
Explain template language

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#19]
The [usability_domain](https://github.com/biocompute-objects/BCO_Specification/blob/master/usability-domain.md) seems to use some kind of template language with examples like `[SO:0000694]`.

I think this is what is alluded to in [external-references](https://github.com/biocompute-objects/BCO_Specification/blob/master/external-references.md)  - but it must be made clear for each field where such `[expansions]` are allowed/expected or not, as well as defining their syntax.

**Comment by HadleyKing** [comment]
@stain or anyone else:
Agreed. I would like to purpose that we use the following: 
* `(SNP)[SO:0000694]` 
where ($term) and [$identifier] are an entry in the `external_references` section. Would writing a simple explanation and editing the example to demonstrate this be enough?
