### ISSUE TITLE
Explain FHIR extension

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#20]
[fhir extension](https://github.com/biocompute-objects/BCO_Specification/blob/master/extension-fhir.md) only shown by example, the keys are not explained. The `camel_Casing` is a bit inconsistent.

James Jones [suggested](https://docs.google.com/a/mygrid.org.uk/document/d/1w7PxAHbv5C-VNbLfelIQUFa6jDxnocaTjDwwUuG0eeY/edit?disco=uiAAAACPFhBC8):

> Can address the camel_Case issues and describe the keys as follows:

> `FHIR_endpoint` is a string containing the URL of endpoint of the FHIR server containing the resource.

> `FHIR_resource` is a string containing the type of resource used. A full list of permitted FHIR resources is available at http://hl7.org/fhir/resourcelist.html.

> `FHIR_ID` is a string containing the server-specific identifier for the resource instance.

> The full URL of each referenced FHIR object is the combined address of the form: `FHIR_endpoint/FHIR_resource/FHIR_ID`

**Comment by stain** [comment]
`Camel_underscore_Casing` is inconsistent, should these perhaps all be lowercase?

**Comment by jpat1546** [comment]
Reopening issue until all inconsistencies have been addressed.

**Comment by mr-c** [comment]
@jpat1546 which commit(s) fixed the remaining inconsistencies?

**Comment by jpat1546** [comment]
> @jpat1546 which commit(s) fixed the remaining inconsistencies?

https://github.com/biocompute-objects/BCO_Specification/commit/6d5b93ccb0c4bff0838400b642bb430a7f141695 

https://github.com/biocompute-objects/BCO_Specification/commit/d4a8333
