### ISSUE TITLE
Refine github extension keys

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#21]
The [github extension](https://github.com/biocompute-objects/BCO_Specification/blob/master/extension-github.md)  is only explained by example.

The two keys `github_repository` and `github_URI` are not explained and seem to be partially overlapping. The `camel_Case` is also inconsistent.

Given that these are URLs I think the extension should support any source control repository, not just github.com, perhaps something like:

```json
"extension_domain":{
  "scm_extension": {
    "scm_repository": "https://github.com/example/repo1",
    "scm_type": "git",
    "scm_branch": "c9ffea0b60fa3bcf8e138af7c99ca141a6b8fb21",
    "scm_path": "workflow/hive-viral-mutation-detection.cwl",
    "scm_preview": "https://github.com/example/repo1/blob/c9ffea0b60fa3bcf8e138af7c99ca141a6b8fb21/workflow/hive-viral-mutation-detection.cwl"
}
```

Here's how Maven defines it's [scm](https://maven.apache.org/pom.html#SCM) metadata.

**Comment by stain** [comment]
Marked as `discuss` - we can keep this simple or general (or something in-between)

**Comment by mr-c** [comment]
I agree, we shouldn't bake in a commercial third party into the BCO spec/standard

**Comment by mr-c** [comment]
Thanks for clarifying, @HadleyKing but I think the example should be updated to match Stian's suggestion.

**Comment by HadleyKing** [comment]
`github_extension` to `scm_extension`

* [ ] user_guide.md:520:        "github_extension": {
* [ ] extension-github.md:9:    "github_extension": {
* [ ] antiviral_resistance_detectionTypeDef.json:23:            "github_extension": {
* [ ] HCV1a.json:91:        "github_extension": {
* [ ] bco-domains.md:22:        "github_extension": {
