### ISSUE TITLE
Clarify script_access_type vs script 

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#26]
[script_access_type](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#251-script-access-type-script_access_type) feels a bit contrived, as it is defining the type of [script](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#252-script-script) key, making it hard to validate/use alone.

The `script` key however does not explain at all how an inline script can be used.

Other parts of BCO use sub-objects like

```json
 "source": {
    "address": "http://example.com/file.txt"
}
```

It might make sense to do a similar approach here, where one can provide either `address` for URI (potentially relative #23 for files) or `value` for inline scripts (but preferably not both!) - thus one can remove `script_access_type`

**Comment by jpat1546** [comment]
Relates to #50

**Comment by HadleyKing** [comment]
See #50.
