### ISSUE TITLE
pipeline_version: Clarify what is a pipeline implementation

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#27]
[pipeline_version](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#253-pipeline-version-pipeline_version) says simply:

> This field records the version of the pipeline implementation.

Anonymous (I think it was me) [questioned](https://docs.google.com/a/mygrid.org.uk/document/d/1w7PxAHbv5C-VNbLfelIQUFa6jDxnocaTjDwwUuG0eeY/edit?disco=AAAABtzGF5U):

> what is a pipeline implementation? Does this mean the version of the `script` above, the pipeline in abstract, or the implementation of the workflow system the pipeline is executed on?

**Comment by HadleyKing** [comment]
At the [BioCompute Spec Hack-a-thon](https://docs.google.com/document/d/1QHW0IBkkPNohgGMBuXz15WNprGl5gJdTAcuk6PThjuQ/edit) is was decided this field has no value here and should be removed. See #50 as well.
