### ISSUE TITLE
platform: What are possible values?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#28]
[platform](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#254-platformenvironment-platform) is defined as:

> The multi-value reference to a particular deployment of an existing platform where this BCO can be reproduced. A platform can be a bioinformatic platform such as Galaxy or HIVE or it can be a software package such as CASAVA or apps that includes multiple algorithms and software.

>     "platform": "HIVE"

1) The example is not actually multi-value

2) Where do the values for `platform` come from? This seems to be free-text, so are we OK with variable values like "Galaxy", "UseGalaxy" and "Galaxy Platform"?

**Comment by HadleyKing** [comment]
> [platform](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#254-platformenvironment-platform) is defined as:
> 
> > The multi-value reference to a particular deployment of an existing platform where this BCO can be reproduced. A platform can be a bioinformatic platform such as Galaxy or HIVE or it can be a software package such as CASAVA or apps that includes multiple algorithms and software.
> 
> > ```
> > "platform": "HIVE"
> > ```
> 
* [x] The example is not actually multi-value
* [ ]  Where do the values for `platform` come from? This seems to be free-text, so are we OK with variable values like "Galaxy", "UseGalaxy" and "Galaxy Platform"?

**Comment by LibrarPotter** [comment]
If the platform information is necessary for retrieving full value from the BCO, a limited vocabulary for communicating the platform information would be valuable; however, I don't know how this list would be populated or maintained.  Does such a list already exist?

**Comment by HadleyKing** [comment]
> > [platform](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#254-platformenvironment-platform) is defined as:
> > > The multi-value reference to a particular deployment of an existing platform where this BCO can be reproduced. A platform can be a bioinformatic platform such as Galaxy or HIVE or it can be a software package such as CASAVA or apps that includes multiple algorithms and software.
> > 
> > 
> > > ```
> > > "platform": "HIVE"
> > > ```
> 
> * [x]  The example is not actually multi-value
> * [x]   Where do the values for `platform` come from? This seems to be free-text, so are we OK with variable values like "Galaxy", "UseGalaxy" and "Galaxy Platform"?

As part of #50 at the [BioCompute Spec Hack-a-thon](https://docs.google.com/document/d/1QHW0IBkkPNohgGMBuXz15WNprGl5gJdTAcuk6PThjuQ/edit) 
this was discussed. Given the difficulty of maintaining a comprehensive list of platforms it does not make sense to have this be a pre-defined value, meaning it has to be free text. 
Having a free text value that is not evaluated in the [`execution_domain`](../blob/master/execution_domain.md) does not make sense either. 
So it was decided to move this field to the [`description_domain`](../blob/master/description_domain.md) and define it as informative and free text.
