### ISSUE TITLE
Fix inconsistent JSON key styles

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#30]
There are some inconsistencies in JSON key names. Generally BCO use `lower_case_with_underscore` which is common in JSON.

Some inconsistencies that unnecessarily deviate from this style should be fixed, for example:

* `Name` in [domain_prerequisites](https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md#257-domain-prerequisites-domain_prerequisites)
* `false discovery` vs `false_discovery` in [error_domain](https://github.com/biocompute-objects/BCO_Specification/blob/master/error-domain.md#28-error-domain-acceptable-range-of-variability-error_domain) examples
* `BCO_id` in [top level](https://github.com/biocompute-objects/BCO_Specification/blob/master/top-level.md#201-biocompute-object-identifier-bco_id) (why not `bco_id` ? )
* [`FHIR_extension`](https://github.com/biocompute-objects/BCO_Specification/blob/master/extension-fhir.md) including `FHIRendpoint_Resource`, `FHIRendpoint_URL` and `FHIRendpoint_Ids`
* `github_URI` in [github_extension](https://github.com/biocompute-objects/BCO_Specification/blob/master/extension-github.md)

**Comment by HadleyKing** [comment]
Agreed on everything but the following:
* `BCO_id` in [top level](https://github.com/biocompute-objects/BCO_Specification/blob/master/top-level.md#201-biocompute-object-identifier-bco_id) (why not `bco_id` ? )

I think that distinguishing the defining field in the BCO is important, and as such the CAPS are appropriate. If anyone disagrees, please convince me.

**Comment by corburn** [comment]
@HadleyKing why is the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) (i.e. be boring/predictable) important?

Take for example the task of entering a URL. How closely do you need to study the specs, cross-reference them with the schema, and cross-reference again with the examples to determine which key should be used in a given section?

Should I use:
- script
- address
- URI
- uri
- Github_URI
- Github_URL
- github_uri
- github_url
- GitHub_url
- Github_Url
- githubURL
- github_URI
- FHIRendpoint_URL
- FHIRendpoint_Resource
- fhir_endpoint_url
- FHIR_endpoint_URL
- FHIR_Endpoint_URL
- FhirEndpointUrl
- FhirEndpointURL
- ...

After determining which key to use, what combination of other keys must be set for a URL to be valid?

If you think the above example is a silly edge-case, consider the BCO

**Comment by corburn** [comment]
@HadleyKing you changed the case of _all_ the fhir* keys to lowercase in the [HCV1a.json](https://github.com/biocompute-objects/BCO_Specification/blob/ab7e7cf86ba1dc5feea19836eed423428d8b9e6f/HCV1a.json#L65-L90) and _most_ of the keys in the [antiviral_resistance_detectionTypeDef.json](https://github.com/biocompute-objects/BCO_Specification/blob/ab7e7cf86ba1dc5feea19836eed423428d8b9e6f/antiviral_resistance_detectionTypeDef.json#L6-L22)

The `FHIR_extension` in the schema was not changed nor were its other occurrences:
https://github.com/biocompute-objects/BCO_Specification/blob/f25293352bd2d806acaf4909717c20ebf1985d74/bco-domains.md#L20

https://github.com/biocompute-objects/BCO_Specification/blob/d0aa195bdbd64ce43291277affcbec7f02cb56a5/user_guide.md#L493

@jpat1546 you closed #20 which cites the same consistency issue without resolving it.
