### ISSUE TITLE
provenance_domain obsolete or obsolete_after

### ISSUE THREAD

**Issue by corburn** [biocompute-objects/BCO_Specification#38]
The specification uses `obsolete`, but the schema uses `obsolete_after`:

./base_type_BioCompute.json:89:            "obsolete_after" : {
./provenance-domain.md:17:        "obsolete" : "2118-09-26T14:43:43-0400",
./provenance-domain.md:105:### 2.1.6 Obsolescence "obsolete" 
./provenance-domain.md:110:"obsolete" : "2118-09-26T14:43:43-0400"
./HCV1a.json:33:        "obsolete" : "2118-09-26T14:43:43-0400",
./user_guide.md:242:            "obsolete_after" : {
./user_guide.md:461:        "obsolete" : "2118-09-26T14:43:43-0400",

**Comment by HadleyKing** [comment]
`obsolete_after` is more informative

**Comment by corburn** [comment]
missed 2 references in e4688f1:

- [x] ./base_type_BioCompute.json:89:            "obsolete_after" : {
- [x] ./provenance-domain.md:17:        "obsolete" : "2118-09-26T14:43:43-0400",
- [x] ./provenance-domain.md:105:### 2.1.6 Obsolescence "obsolete" 
- [x] ./provenance-domain.md:110:"obsolete" : "2118-09-26T14:43:43-0400"
- [ ] ./HCV1a.json:33:        "obsolete" : "2118-09-26T14:43:43-0400",
- [x] ./user_guide.md:242:            "obsolete_after" : {
- [ ] ./user_guide.md:461:        "obsolete" : "2118-09-26T14:43:43-0400",
