### ISSUE TITLE
digital signature: needs work

### ISSUE THREAD

**Issue by mr-c** [biocompute-objects/BCO_Specification#43]
How to generate using MD5? (can't include a signature inside itself)

- [x] I recommend another field to specify the algorithm

**Comment by HadleyKing** [comment]
The PDF spec agreed on SHA-256 as the hash function. I do not know how we got away from that, but I fixed it here.

**Comment by mr-c** [comment]
A hash is not a digital signature. I suggest we rename this field to "hash"

**Comment by anton-golikov** [comment]
Maybe 'checksum'?
