### ISSUE TITLE
provide 2 platform specific structures for the IO domain

### ISSUE THREAD

**Issue by mr-c** [biocompute-objects/BCO_Specification#47]
Starting with the platforms of interest to FDA: HIVE & CWL

Other platforms can be defined by each vendor/language community.

**Comment by HadleyKing** [comment]
As explained here: https://github.com/biocompute-objects/BCO_Specification/issues/11#issuecomment-442499008
the use of [`data typing` ](../blob/master/data-typing.md) for individual BCOs should not be necessary  anymore. therefore I think this issue would serve better as "provide 2 platform specific examples for BCO"
I have started a repo for a new [HIVE example](https://github.com/biocompute-objects/HIVE_metagenomics).

**Comment by HadleyKing** [comment]
@mr-c I think the schema should be good to go for an example.

**Comment by HadleyKing** [comment]
See [UVP.json](https://github.com/biocompute-objects/UVP-BCO/blob/master/UVP.json)
