### ISSUE TITLE
Define BCO in JSON Schema?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#5]
- [ ] Link to @corburn's [JSON Schema for BCO](https://github.com/biocompute-objects/BCO_Specification/pull/34/files#diff-05b48ab5ec77428bb5e3d302d66fa1c8) in the README

Instead of the custom BCO data type schema with `_type` etc (which itself does not have any documentation), we should use something like [JSON Schema](https://json-schema.org/) which have multiple tools and validators.

Note that JSON Schema itself is [working towards RFC](https://json-schema.org/#update-as-of-9-september-2018) so there might be finer details here changing, but I would argue it is still a more mature schema language for defining expected JSON types than the one we blindly use in [primitives.json](https://github.com/biocompute-objects/BCO_Specification/blob/master/primitives.json)

**Comment by corburn** [comment]
@jpat1546 I think I could have this done today, would it be alright with you if I give this a go?
