### ISSUE TITLE
Execution Domain

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#50]
Issues from [execution-domain](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-execution-domain.md)

- [x] Maybe script_access_type and script properities can be tied together (#26)
- [x] script.uri
   URI values require regex
- [x] pipeline_version should not be required (is listed as required in schema)
   (maybe it is not necessary here) 
- [x]  platform maybe not needed in this domain

In general, this domain needs more refinement

- [x] domain_prerequisites should be renamed (maybe "data_endpoint")
   domain_prerequisites.name should also be renamed
   regex for domain_prerequisites.url 
- [x] env_parameters should a simple dictionary of a list of dictionaries
   Should avoid saying "Environmental parameters" --> should be environment variables

**Comment by corburn** [comment]
@HadleyKing in regards to 98c53dc resolving [extra-validation-items-execution-domain.md](https://github.com/biocompute-objects/bco_verifier/blob/9297e387a87bb02d7427cc262a1ba324d8bb9566/extra-validation-items-execution-domain.md):
>6. env_parameters should a simple dictionary of a list of dictionaries Should avoid saying "Environmental parameters" --> should be environment variables

It looks like the idea was to change this:
```json
"env_parameters": [{
    "key": "HOSTTYPE", 
    "value" : "x86_64-linux"
}]
```

to this:
```json
"environment_variables": {
    "HOSTTYPE": "x86_64-linux",
    "EDITOR": "vim",
    "FOO_BAR": "baz_quox"
}
```

**Comment by HadleyKing** [comment]
@corburn 
ok. How would that look in the schema? I was unsure of how to implement that.

**Comment by HadleyKing** [comment]
@corburn 
> Issues from [execution-domain](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-execution-domain.md)
> 
> * [ ]  Maybe script_access_type and script properities can be tied together (#26)

I was also trying to implement some sort of `enum` or `oneOf` for the `script` field to accommodate the possibility of two different types (e.g. `uri` or `text`) and referencing them as #definition, but could not get it to work. I think that would allow us to combine these fields into one. It would also solve the bullet below too... I think. 

> * [ ]  script.uri
>   URI values require regex

**Comment by corburn** [comment]
@HadleyKing 

### environment_variables schema:

```json
    "environment_variables": {
      "type": "object",
      "description": "Environmental parameters that are useful to configure the execution environment on the target platform.",
      "patternProperties": {
        "^[a-zA-Z_]+[a-zA-Z0-9_]*$": {
          "type": "string"
        }
      }
    }
```

The regex is based on the following:

>http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html
>Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities.
>
>Note:
Other applications may have difficulty dealing with environment variable names that start with a digit. For this reason, use of such names is not recommended anywhere.

### script and script_access_type

I would drop `script_access_type` and define `script` simply as a URI:

https://tools.ietf.org/html/rfc8089
file://path/to/rfc8089.txt
