### ISSUE TITLE
Extension domain issues

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#51]
Issues from [extension_domain-fhir.md](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-extension_domain-fhir.md)

- [x] fhir_endpoint regex for URL (since format is specified, maybe it is already being validated in the first level)
- [x] fhir_version regex [0-9]

Issues from [extension_domain-scm.md](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-extension_domain-scm.md)

- [x] scm_extension.scm_repository, scm_extension.scm_preview 
    regex for URL (maybe this is already being validated at the first level)
- [x] scm_extension.scm_preview is listed as required in schema but it 
   should not be required  
- [ ] scm_extension.scm_path should not be uri-reference (as described in schema)

**Comment by corburn** [comment]
# fhir_version regex [0-9]

If only numbers are valid and not `v3-beta2`, the `type` or `format` could be defined as integer/number.

## Current Definition

https://github.com/biocompute-objects/BCO_Specification/blob/05d02cbf4564805fe680cefffbaf1014a5f10d0d/schemas/extension_domain/fhir_extension.json#L19-L22

## Alternative Definitions

Integer
```json
"fhir_version": { 
   "type": "integer", 
   "description": "FHIR version of the server endpoint" 
 },

"fhir_version": 42
```

Number (integer or float/decimal)
```json
"fhir_version": { 
   "type": "number", 
   "description": "FHIR version of the server endpoint" 
 },

"fhir_version": 42
"fhir_version": 42.0
```

Text number
```json
"fhir_version": { 
   "type": "string", 
   "description": "FHIR version of the server endpoint",
   "format": "number"
 },

"fhir_version": "42"
```

Pattern/Regex
```json
"fhir_version": { 
   "type": "string", 
   "description": "FHIR version of the server endpoint",
  "pattern": "\d+(\.\d+)?"
 },

"fhir_version": "42"
```

**Comment by HadleyKing** [comment]
> Issues from [extension_domain-fhir.md](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-extension_domain-fhir.md)
> 
> * [x]  fhir_endpoint regex for URL (since format is specified, maybe it is already being validated in the first level)

            "format": "uri"

> * [x]  fhir_version regex [0-9]

As we have not received clear feedback on how this will be implemented in the future (with FHIR) we will leave it as a             "type": "string",

> Issues from [extension_domain-scm.md](https://github.com/biocompute-objects/bco_verifier/blob/master/extra-validation-items-extension_domain-scm.md)
> 
> * [x]  scm_extension.scm_repository, scm_extension.scm_preview
>   regex for URL (maybe this is already being validated at the first level)

            "format": "uri"

> * [x]  scm_extension.scm_preview is listed as required in schema but should not be required

Fixed 

> * [x]  scm_extension.scm_path should not be uri-reference (as described in schema)

            "type": "string",
