### ISSUE TITLE
biocomputeobjects.org/schema

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#53]
@kee007ney 
We should have _something_ at biocomputeobjects.org/schema

**Comment by mr-c** [comment]
And this is what https://w3id.org/biocompute/spec/v1.2 (or similar) should redirect to

**Comment by kee007ney** [comment]
@mr-c I might have misunderstood -- I built https://biocomputeobject.org/schema.html and made it point to the permalink you included. After having done that, it's feeling like that might not be what you meant? Did I understand that correctly or were you suggesting something else?

**Comment by HadleyKing** [comment]
The re-directs need to be finished by the release of v1.4.0
