### ISSUE TITLE
remove 'additionalProperties: false' 

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#54]
>TODO: remove 'additionalProperties: false' after handling inherited types is resolved. In the meantime it was set to avoid forgetting to write a schema for a new property because it is silently ignored during validation"

This should be done after resolving #11

**Comment by HadleyKing** [comment]
@corburn Can we do this and close?

**Comment by corburn** [comment]
@HadleyKing yes.
