### ISSUE TITLE
Develop  a spec release protocol

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#57]
We need to develop a spec release protocol so we can update in an orderly fashion. A few suggestions for what it should contain to start:
* method explained for versioning based on [Semantic Versioning](https://semver.org) and utilizing [Permanent Identifiers for the Web](https://w3id.org/)

* Method for issue triage, I.E. how are issues/suggestions handled? What about ideas for future development or implementation? 

Also, where should these policies be stated? In the README, in a new user guide, or in a new document?

**Comment by nsoranzo** [comment]
I'd suggest to state this in a different document, not the main README.

**Comment by HadleyKing** [comment]
@nsoranzo  
Looking at the Galaxy releases it seems that the doc lists each commit incorporated? is that automatic?

**Comment by nsoranzo** [comment]
Yep, the release notes are generated by the scripts/bootstrap_history.py script, invoked via `make release-bootstrap-history`
