### ISSUE TITLE
bco-specification.md delete section 3.4 or specify JSON Schema

### ISSUE THREAD

**Issue by corburn** [biocompute-objects/BCO_Specification#58]
[bco-specification.md section 3.4](https://github.com/biocompute-objects/BCO_Specification/blob/f7f30997a4a882b7b8151838fc78753bcf263c17/bco-specification.md#34-appendix-v-data-typing) references data-typing.md which was discontinued in e9686c163ac9c1ebf9f5aa4761a26115195ba867

>## 3.4 Appendix V Data typing
>
>The conceptual schema for BCO creation can be defined in `???` schema language. 
>
>Specifications:
>
>* [Data Typing](data-typing.md)

**Comment by HadleyKing** [comment]
> [bco-specification.md section 3.4](https://github.com/biocompute-objects/BCO_Specification/blob/f7f30997a4a882b7b8151838fc78753bcf263c17/bco-specification.md#34-appendix-v-data-typing) references data-typing.md which was discontinued in [e9686c1](https://github.com/biocompute-objects/BCO_Specification/commit/e9686c163ac9c1ebf9f5aa4761a26115195ba867)

- Removed this text
 
> > ## 3.4 Appendix V Data typing
> > The conceptual schema for BCO creation can be defined in `???` schema language. 
> > Specifications:
> > 
> > * [Data Typing](data-typing.md)

I think it would be good to explain JSON as our chosen schema and to also mention the `definitions`
https://github.com/biocompute-objects/BCO_Specification/blob/9fd348e71a5650b6e024dbd29e0477627864cb62/schemas/biocomputeobject.json#L19-L127

Maybe in the [Top Level](https://github.com/biocompute-objects/BCO_Specification/blob/master/top-level.md#20-top-level-fields)? 

Anyone  else want to take a crack at it?
