### ISSUE TITLE
License of the BCO Specification repository?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#6]
What should be the license of this `BCO_Specification` repository? Presumably we want this to be Open Access as it's on GitHub and our IEEE Open Source Pilot part will reference this repo?

Normally for documents [Creative Commons BY 4.0](https://creativecommons.org/licenses/by/4.0/) is a good choice, however it is [not recommended](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) for software.

A technical specification with various JSON examples is somewhat in-between a Document and Software. The line moves more towards Software when we introduce formal schemas that implementer might want to copy into their code.

So our license should presumably be something that is easy to integrate into other commercial and open source projects, like [Apache License v2.0](https://www.apache.org/licenses/LICENSE-2.0) which conveniently also cover [contributions](https://www.apache.org/licenses/LICENSE-2.0#contributions)  as well as [protection against patent traps](https://www.apache.org/licenses/LICENSE-2.0#patent).

Note that for relicensing we should ideally ask for permission from every BCO copyright holder as the previous Google Docs document never had a license or Intellectual Property section. In reality only those who contributed "substantial work" (e.g. a paragraph) would own copyright.

# Conflict of interest
Note that I am probably biased above. I am both a [Apache Software Foundation](https://www.apache.org/) member and on the [Common Workflow Language](https://www.commonwl.org/) leadership team, which [use Apache License](https://github.com/common-workflow-language/common-workflow-language/blob/master/LICENSE.txt) for the CWL specifications.

**Comment by rajamazumder** [comment]
We have chosen to apply the GNU General Public License, version 3 (GPL-3.0)
(http://opensource.org/licenses/GPL-3.0) to all parts of our databases,
datasets and tools.

-- 
Raja Mazumder, Ph.D.
Associate Professor
Department of Biochemistry and Molecular Medicine
School of Medicine & Health Sciences
The George Washington University
Ross Hall, Room 540
2300 Eye Street N.W.
Washington, DC 20037
Phone office: 202-994-5004
Phone lab: 202-994-3639
Phone dept: 202-994-5311
Fax: 202-994-8974

**Comment by mr-c** [comment]
FYI, the last draft of the IEEE-SA Open Source Policy & Procedures I saw says that the only licenses allowed are Apache 2.0 and BSD 3-Clause.

**Comment by stain** [comment]
Both Apache 2.0 and BSD 3-Clause are permissive licenses, so either would permit work from the BCO Spec (e.g. a JSON example) to be relatively easily included in an open source or commercial implementation.

For instance both Apache2.0 and BSD 3-Clause are 'upwards' compatible with GPL 3.0, treating the combined work as GPL 3.0.

BSD 3-Clause could also be included in GPL 2.1 code that have removed the GPL license update clause. (Such code would however have trouble with including GPL 3.0 code)

One thing is, with BSD 3-Clause we would need to keep collecting Contributor License Agreements so that later contributions can be distributed under BSD 3-Clause - at least if those contributions are going back to IEEE.

BSD 3-Clause does not have a Patent License Grant, but perhaps that is somewhat included in the IEEE agreements? In that case we can only accept contributions from those who have signed the IEEE contributor agreement (perhaps this can also be part of our CLA).

**Comment by stain** [comment]
What is the decision on the license?

**Comment by stain** [comment]
@kee007ney says second IEEE meeting agreed license to be BSD 3-Clause.
