### ISSUE TITLE
separation of input Files and other input parameters clashes with CWL's object model

### ISSUE THREAD

**Issue by mr-c** [biocompute-objects/BCO_Specification#63]
In CWL inputs can be of type File or Directory, as well as string, or various types of numbers. Additionally we have complex types (lists, records/maps).

In BCO there is currently a mixed "IO" domain for input/output files and a seperate [`parametric_domain`](https://github.com/biocompute-objects/BCO_Specification/blob/master/schemas/parametric_domain.json) that has only inputs of type "string", so no room for other types of inputs.

This means that auto-generating a BCO from the execution of a CWL workflow will be difficult, and potentially impossible. It is likely that other workflow models will have a similar problem.

**Comment by HadleyKing** [comment]
Suggestions on how to address this? 
Is there an example we can use that does fit the current BCO model?

**Comment by HadleyKing** [comment]
My thoughts: The binning of these values is for conceptual understanding of how a pipeline was implemented (communication purposes), not explicitly to RUN the pipeline. A CWL workflow would be PART of the BCO and as such would still contain all the info represented by the CWL object in the CWL model. 

I would like to try two possible examples if some one can point me to them: 
1) CWL object that fits the BCO model very well and 
2) CWL object that does not
