### ISSUE TITLE
needs formal reference to draft-handrews-json-schema-validation-01

### ISSUE THREAD

**Issue by mr-c** [biocompute-objects/BCO_Specification#64]
a.k.a https://json-schema.org/latest/json-schema-validation.html

This is where `readOnly` is defined, though it would be good for use to think through that definition in the context of the BCO use case(s).

**Comment by HadleyKing** [comment]
https://tools.ietf.org/html/draft-handrews-json-schema-01

**Comment by HadleyKing** [comment]
https://json-schema.org/specification-links.html#draft-7
