### ISSUE TITLE
IO as a Block?

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#70]
From @NuriaGuimera: 
Can we include the input and output files as a block or they should be included individually?

**Comment by HadleyKing** [comment]
Once we incoorperate (https://tools.ietf.org/html/draft-handrews-json-schema-validation-02)[draft-handrews-json-schema-validation-02] I think this will be much more clear.

**Comment by HadleyKing** [comment]
I am thinking that we can model this after the way Galaxy does `collections`. @nsoranzo your thoughts? I'm still not sure I understand how collections are created.

**Comment by nsoranzo** [comment]
An overview of dataset collections in Galaxy: https://galaxyproject.org/tutorials/collections/
