### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#80]
Should we implement the use of Git Wikis for V2.0? 
Are there any downsides?

**Comment by corburn** [comment]
No, wikis tend to be filled with documentation and are a mess to maintain. When documentation is kept in the repository it is current for the revision that is checked out. When documentation is kept in a wiki, decoupled from the repository, it is current for whenever the segment was last updated. Github Wikis are not easily searched. For anything that is not documentation, Github Issues are at least searchable, revisable, and referable.
