### ISSUE TITLE
Execution domain: different environmental variables

### ISSUE THREAD

**Issue by jiugeyang** [biocompute-objects/BCO_Specification#83]
Hi everyone,

An issue came to me when I was developing a future BCO. The current specification documents (quoted below) only give instructions on how to document a single set of environmental variables in the execution domain. 
```
{"environment_variables": {
            "HOSTTYPE": "x86_64-linux",
            "EDITOR": "vim"
        }
 }
```
However, if a pipeline were executed on multiple platforms(e.g.HIVE one and HIVE AWS), there would be two or more different sets of environmental variables. How would these environmental variables be documented? Please let me know. Thanks!

**Comment by HadleyKing** [comment]
We should develop a response to this and include in the FAQ release for March

**Comment by HadleyKing** [comment]
Since the `environment_variables` is essentially free text a BCO writer could represent that any way they choose, but my recommendation would be to do something like the following: 
``` JSON
{"environment_variables": {
            "HOSTTYPE_local": "x86_64-linux",
            "EDITOR_local": "vim",
            "HOSTTYPE_AWS": "x86_64-linux",
            "EDITOR_AWS": "vim"
        }
 }
