### ISSUE TITLE
release_1.4.0

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#86]
- [x] **Prep**
     - ~~[x] Create a release issue: release_1.4.0.~~
     - [ ] Set freeze date freeze date [TBD]
 - [ ] **Branch Release (on or around freeze date)**
     - [ ] Ensure all [blocking milestone issues](https://github.com/biocompute-objects/BCO_Specification/milestones) have been closed.
     - [ ] Merge the latest release into dev and push upstream.
 - [ ] **Deploy and Test Release**
     - [x] Review issues and ensure they all have a milestones attached. [Link](https://github.com/biocompute-objects/BCO_Specification/milestones)
     - [ ] Checkout release branch.
	 - [ ] Run `schemas/validate.py` on each of the examples in `examples/*`, updating if necessary.
     - [ ] Check for obvious missing or inconsistent documentation in release.
 - [ ] **Create Release Notes**
     - [ ] Open newly edited/created files and manually curate for accuracy.
     - [ ] If any changes are made, ensure you commit branch again and document in commit what was changed.
     - [ ] Run `sh scripts/log.sh` from the repo root.
     - [ ] Check for obvious missing or inconsistent documentation in release notes (`CHANGELOG.md`).
     - [ ] Commit branch.
 - [ ] **Do Release**
     - [ ] Ensure all [blocking milestone issues](https://github.com/biocompute-objects/BCO_Specification/milestones) have been resolved.
     - [ ] Create and push new release tag.
 - [ ] **Announce Release**
     - [ ] Verify release included in https://github.com/biocompute-objects/BCO_Specification/releases
     - [ ] Review announcement on **https://biocomputeobject.org/**
     - [ ] Tweet docs news *highlights* link as @BioComputeObj on twitter. [@kee007ney will provide an example in the future](https://twitter.com/BioComputeObj).
     - [ ] Email *highlights* to listserv [@kee007ney will provide an example in the future](https://twitter.com/BioComputeObj)..

 - [ ] **Prepare for next release**
     - [ ] Close milestone ``${version}`` and ensure milestone ``${next_version}`` exists.
     - [ ] Create release issue for next version ``release_${next_version}``.
     - [ ] Close this issue.

**Comment by stain** [comment]
We also need to remove or update the [schema files](https://github.com/biocompute-objects/BCO_Specification/tree/1.4.0/schemas) to match exactly https://gitlab.com/IEEE-SA/2791/ieee-2791-schema (including their LICENSE/COPYRIGHT). In particular notice:

```json
"spec_version": "https://w3id.org/2791/"
```

**Comment by stain** [comment]
I checked if the user guide is updated to match IEEE 2791-2020, but https://github.com/biocompute-objects/BCO_Specification/blob/1.4.0/docs/bco-domains.md#bco-domains says 1.3.0 in its `spec_version`.

The user guide no longer link or include the JSON schema files from https://gitlab.com/IEEE-SA/2791/2791-schema/ 

Many of the other pages have too strong recommendations compared to the standard, e.g. [ETag](https://github.com/biocompute-objects/BCO_Specification/blob/1.4.0/docs/top-level.md#203-etag-etag) mentions SHA256, but that would just be one of many ways to calculate it. 


References to `xref` in https://github.com/biocompute-objects/BCO_Specification/blob/1.4.0/docs/usability-domain.md seem unfounded from IEEE spec/schema as [usability_domain.json](https://gitlab.com/IEEE-SA/2791/2791-schema/-/blob/master/usability_domain.json) just say free text, while we find in user guide:

> The usability_domain can accept template language to indicate values from the external_references.

This template language is not defined by IEEE 2791.

So overall these kind of general guidances or best practices (which do not exist in IEEE standard) should be separated out from guidance on what is **required** from the specification.

**Comment by HadleyKing** [comment]
@stain 
 I posted an [issue](https://gitlab.com/IEEE-SA/2791/2791-schema/-/issues/5) about the URLs. 
Not sure if Josh has seen it. @kee007ney  or I will try to reach out again. 
``` json
        "spec_version": {
            "type": "string",
            "description": "Version of the IEEE-2791 specification used to define this document",
            "examples": [
                "https://w3id.org/2791/"
```
The current schema files are a direct copy of the IEEE files, but they need to be addressed. 
https://gitlab.com/IEEE-SA/2791/2791-schema/-/blob/master/2791object.json#L120
