### ISSUE TITLE
Include IEEE 2791 schema files

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Specification#88]
We need to remove or update the [schema files](https://github.com/biocompute-objects/BCO_Specification/tree/1.4.0/schemas) to match exactly (now public) https://gitlab.com/IEEE-SA/2791/ieee-2791-schema (including their LICENSE/COPYRIGHT). 

In particular notice:

```json
"spec_version": "https://w3id.org/2791/"
```

so I guess there should not be any cases of `http://www.w3id.org/biocompute/1.4.0` etc.

**Comment by stain** [comment]
There's (or should be) a discussion with Josh at IEEE if the w3id permalink should be `/2791` or `/ieee/2791` under the existing (empty) [folder /ieee](https://github.com/perma-id/w3id.org/tree/master/ieee) - the [gitlab schemas](https://gitlab.com/IEEE-SA/2791/2791-schema/-/tree/master) and standards doc needs to be updated to match outcome of that discussion.

I see the files are now added in https://github.com/biocompute-objects/BCO_Specification/tree/1.4.0/ieee-2791-schema - the version/commit it is from is probably important to note in the text. They need to be linked to from the user guide.

**Comment by HadleyKing** [comment]
IEEE permalinks and schema files have been updated via https://github.com/biocompute-objects/BCO_Specification/commit/be65ecb2019badd928b3079973f3910802678709
