### ISSUE TITLE
Documentation Home broken links

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#99]
Broken links:
- [x] [this repository](https://docs.biocomputeobject.org/#Repository) Link - unresponsive. 
- [ ] [BSD 3-Clause “New” or “Revised” License](https://docs.biocomputeobject.org/LICENSE) -Ends in 404 pages

**Comment by jpat1546** [comment]
License link not fixed--

tried:
`BCO_Specification is licensed under the [BSD 3-Clause "New" or "Revised" License](./LICENSE.md)`
`BCO_Specification is licensed under the [BSD 3-Clause "New" or "Revised" License](/LICENSE.md)
`
Still 404 Broken link

**Comment by HadleyKing** [comment]
Try this:

`[BSD 3-Clause "New" or "Revised" License](/LICENSE)`

**Comment by jpat1546** [comment]
> Try this:
> 
> `[BSD 3-Clause "New" or "Revised" License](/LICENSE)`

https://github.com/biocompute-objects/BCO_Specification/commit/a48d333bdbf2653f8f977388f679636f77ab8dd9 

tried, didn't work :(

**Comment by jpat1546** [comment]
workaround https://github.com/biocompute-objects/BCO_Specification/commit/f0d3b05c9a771ac5bd44283c54752ad3582dd6c5
